#!c:\users\zquan\documents\cs_files\ecs193ab\ecs193a-prototype\genomics_browser_venv\scripts\python.exe
import pcsv
from jtutils import fix_broken_pipe

if __name__ == "__main__":
    fix_broken_pipe()
    pcsv.pcsv()
