# Generated by Django 3.2.17 on 2023-02-10 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='', max_length=50)),
                ('gene_ids', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('gene_values', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('dataset_id', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
            ],
        ),
    ]
