# Generated by Django 3.2.17 on 2023-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomics_browser_django_app_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_db',
            name='dataset_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='gene_ids',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='gene_values',
            field=models.CharField(default='', max_length=50),
        ),
    ]
